#######################################################
##  Platform Securitas, adds sensor and arming switches
#######################################################

securitas:
    # Name for components
    name: "Home Alarm"
    # Username - your username to Securitas
    username: !secret securitas_user
    # Password - your password to Securitas
    password: !secret securitas_pw