###################################
##  Switch for on/off control
###################################
switch:
  - platform: securitasswitch
    # Name - the name you want to give your alarm in Home Assistant
    name: "Home Alarm"
    # Username - your username to Securitas
    username: "username"
    # Password - your password to Securitas
    password: "password"